"""
Automatically translated from C++ to Python

Original file: include/Book.h
Module: Book

This code was generated by an AI-powered code translation system.
Please review and test before using in production.
"""

class Book:
    def __init__(self, isbn: str, title: str, author: str, year: int):
        self._isbn = isbn
        self._title = title
        self._author = author
        self._publication_year = year
        self._is_available = True
        self._categories = []

    # Getters
    def get_isbn(self) -> str:
        return self._isbn

    def get_title(self) -> str:
        return self._title

    def get_author(self) -> str:
        return self._author

    def get_publication_year(self) -> int:
        return self._publication_year

    def get_availability(self) -> bool:
        return self._is_available

    def get_categories(self) -> list:
        return self._categories

    # Setters
    def set_availability(self, available: bool):
        self._is_available = available

    def add_category(self, category: str):
        if category not in self._categories:
            self._categories.append(category)

    # Utility
    def display_info(self):
        print(f"ISBN: {self._isbn}")
        print(f"Title: {self._title}")
        print(f"Author: {self._author}")
        print(f"Publication Year: {self._publication_year}")
        print(f"Available: {'Yes' if self._is_available else 'No'}")
        print("Categories: " + ", ".join(self._categories))

    def matches_search(self, query: str) -> bool:
        query_lower = query.lower()
        return (query_lower in self._isbn.lower() or
                query_lower in self._title.lower() or
                query_lower in self._author.lower())