"""
Automatically translated from C++ to Python

Original file: include/Library.h
Module: Library

This code was generated by an AI-powered code translation system.
Please review and test before using in production.
"""

# library.py

from typing import Dict, List, Optional
from book import Book
from user import User

class Library:
    def __init__(self, name: str):
        self.library_name: str = name
        self.books: Dict[str, Book] = {}
        self.users: Dict[str, User] = {}
        self.total_borrowed_count: int = 0

    # Book management
    def add_book(self, book: Book) -> bool:
        if book.isbn in self.books:
            return False
        self.books[book.isbn] = book
        return True

    def remove_book(self, isbn: str) -> bool:
        if isbn in self.books:
            del self.books[isbn]
            return True
        return False

    def find_book(self, isbn: str) -> Optional[Book]:
        return self.books.get(isbn)

    def search_books(self, query: str) -> List[Book]:
        return [book for book in self.books.values() if query.lower() in book.title.lower()]

    # User management
    def register_user(self, user: User) -> bool:
        if user.user_id in self.users:
            return False
        self.users[user.user_id] = user
        return True

    def remove_user(self, user_id: str) -> bool:
        if user_id in self.users:
            del self.users[user_id]
            return True
        return False

    def find_user(self, user_id: str) -> Optional[User]:
        return self.users.get(user_id)

    # Borrowing system
    def borrow_book(self, user_id: str, isbn: str) -> bool:
        user = self.find_user(user_id)
        book = self.find_book(isbn)
        if user and book and not book.is_borrowed:
            book.is_borrowed = True
            user.borrowed_books.append(book)
            self.total_borrowed_count += 1
            return True
        return False

    def return_book(self, user_id: str, isbn: str) -> bool:
        user = self.find_user(user_id)
        book = self.find_book(isbn)
        if user and book and book.is_borrowed:
            book.is_borrowed = False
            user.borrowed_books.remove(book)
            self.total_borrowed_count -= 1
            return True
        return False

    # Statistics
    def get_total_books(self) -> int:
        return len(self.books)

    def get_available_books(self) -> int:
        return sum(1 for book in self.books.values() if not book.is_borrowed)

    def get_total_users(self) -> int:
        return len(self.users)

    def get_total_borrowed(self) -> int:
        return self.total_borrowed_count

    # Display
    def display_library_info(self) -> None:
        print(f"Library Name: {self.library_name}")
        print(f"Total Books: {self.get_total_books()}")
        print(f"Available Books: {self.get_available_books()}")
        print(f"Total Users: {self.get_total_users()}")
        print(f"Total Borrowed Books: {self.get_total_borrowed()}")

    def display_all_books(self) -> None:
        for book in self.books.values():
            print(book)

    def display_all_users(self) -> None:
        for user in self.users.values():
            print(user)