"""
Automatically translated from C++ to Python

Original file: include/LibrarySystem.h
Module: LibrarySystem

This code was generated by an AI-powered code translation system.
Please review and test before using in production.
"""

# library_system.py

from library import Library
from transaction_manager import TransactionManager

class LibrarySystem:
    def __init__(self, library_name: str):
        self.library = Library(library_name)
        self.transaction_manager = TransactionManager()
        self.is_initialized = False

    def initialize(self) -> bool:
        try:
            # Assuming initialize methods for library and transaction manager
            self.library.initialize()
            self.transaction_manager.initialize()
            self.is_initialized = True
            return True
        except Exception as e:
            print(f"Initialization failed: {e}")
            return False

    def shutdown(self):
        try:
            # Assuming shutdown methods for library and transaction manager
            self.library.shutdown()
            self.transaction_manager.shutdown()
            self.is_initialized = False
        except Exception as e:
            print(f"Shutdown failed: {e}")

    def borrow_book_with_transaction(self, user_id: str, isbn: str) -> bool:
        if not self.is_initialized:
            print("System not initialized.")
            return False
        try:
            if self.library.borrow_book(user_id, isbn):
                self.transaction_manager.log_transaction(user_id, isbn, "borrow")
                return True
            return False
        except Exception as e:
            print(f"Borrowing book failed: {e}")
            return False

    def return_book_with_transaction(self, user_id: str, isbn: str) -> bool:
        if not self.is_initialized:
            print("System not initialized.")
            return False
        try:
            if self.library.return_book(user_id, isbn):
                self.transaction_manager.log_transaction(user_id, isbn, "return")
                return True
            return False
        except Exception as e:
            print(f"Returning book failed: {e}")
            return False

    def generate_user_report(self, user_id: str):
        try:
            # Assuming a method to generate user report
            self.library.generate_user_report(user_id)
        except Exception as e:
            print(f"Generating user report failed: {e}")

    def generate_book_report(self, isbn: str):
        try:
            # Assuming a method to generate book report
            self.library.generate_book_report(isbn)
        except Exception as e:
            print(f"Generating book report failed: {e}")

    def generate_system_report(self):
        try:
            # Assuming a method to generate system report
            self.library.generate_system_report()
        except Exception as e:
            print(f"Generating system report failed: {e}")

    def get_library(self) -> Library:
        return self.library

    def get_transaction_manager(self) -> TransactionManager:
        return self.transaction_manager