"""
Automatically translated from C++ to Python

Original file: include/Transaction.h
Module: Transaction

This code was generated by an AI-powered code translation system.
Please review and test before using in production.
"""

from enum import Enum
from datetime import datetime

class TransactionType(Enum):
    BORROW = 'BORROW'
    RETURN = 'RETURN'
    RENEW = 'RENEW'

class Transaction:
    def __init__(self, transaction_id: str, user_id: str, isbn: str, type: TransactionType):
        self._transaction_id = transaction_id
        self._user_id = user_id
        self._isbn = isbn
        self._type = type
        self._timestamp = datetime.now()

    # Getters
    def get_transaction_id(self) -> str:
        return self._transaction_id

    def get_user_id(self) -> str:
        return self._user_id

    def get_isbn(self) -> str:
        return self._isbn

    def get_type(self) -> TransactionType:
        return self._type

    def get_timestamp(self) -> datetime:
        return self._timestamp

    # Display
    def display_transaction(self) -> None:
        print(f"Transaction ID: {self._transaction_id}")
        print(f"User ID: {self._user_id}")
        print(f"ISBN: {self._isbn}")
        print(f"Type: {self.get_type_string()}")
        print(f"Timestamp: {self._timestamp}")

    def get_type_string(self) -> str:
        return self._type.value

# Example usage:
# transaction = Transaction("TX123", "U456", "978-3-16-148410-0", TransactionType.BORROW)
# transaction.display_transaction()