"""
Automatically translated from C++ to Python

Original file: include/TransactionManager.h
Module: TransactionManager

This code was generated by an AI-powered code translation system.
Please review and test before using in production.
"""

from typing import List, Optional
from transaction import Transaction, TransactionType

class TransactionManager:
    def __init__(self):
        self.transactions: List[Transaction] = []
        self.next_transaction_id: int = 0

    def record_transaction(self, user_id: str, isbn: str, transaction_type: TransactionType) -> str:
        transaction_id = f"TX{self.next_transaction_id}"
        transaction = Transaction(transaction_id, user_id, isbn, transaction_type)
        self.transactions.append(transaction)
        self.next_transaction_id += 1
        return transaction_id

    def get_user_transactions(self, user_id: str) -> List[Transaction]:
        return [tx for tx in self.transactions if tx.user_id == user_id]

    def get_book_transactions(self, isbn: str) -> List[Transaction]:
        return [tx for tx in self.transactions if tx.isbn == isbn]

    def get_transaction(self, tx_id: str) -> Optional[Transaction]:
        for tx in self.transactions:
            if tx.transaction_id == tx_id:
                return tx
        return None

    def get_total_transactions(self) -> int:
        return len(self.transactions)

    def get_transactions_by_type(self, transaction_type: TransactionType) -> int:
        return sum(1 for tx in self.transactions if tx.transaction_type == transaction_type)

    def display_all_transactions(self) -> None:
        for tx in self.transactions:
            print(tx)

    def display_recent_transactions(self, count: int = 10) -> None:
        for tx in self.transactions[-count:]:
            print(tx)