"""
Automatically translated from C++ to Python

Original file: include/User.h
Module: User

This code was generated by an AI-powered code translation system.
Please review and test before using in production.
"""

class User:
    def __init__(self, user_id, name, email, max_books=5):
        self.user_id = user_id
        self.name = name
        self.email = email
        self.borrowed_books = []
        self.max_books_allowed = max_books

    # Getters
    def get_user_id(self):
        return self.user_id

    def get_name(self):
        return self.name

    def get_email(self):
        return self.email

    def get_borrowed_book_count(self):
        return len(self.borrowed_books)

    def can_borrow_more(self):
        return len(self.borrowed_books) < self.max_books_allowed

    # Book management
    def borrow_book(self, isbn):
        if self.can_borrow_more() and isbn not in self.borrowed_books:
            self.borrowed_books.append(isbn)
            return True
        return False

    def return_book(self, isbn):
        if isbn in self.borrowed_books:
            self.borrowed_books.remove(isbn)
            return True
        return False

    def has_borrowed(self, isbn):
        return isbn in self.borrowed_books

    # Display
    def display_info(self):
        print(f"User ID: {self.user_id}")
        print(f"Name: {self.name}")
        print(f"Email: {self.email}")
        print(f"Borrowed Books: {', '.join(self.borrowed_books)}")
        print(f"Max Books Allowed: {self.max_books_allowed}")