"""
Automatically translated from C++ to Python

Original file: include/Utils.h
Module: Utils

This code was generated by an AI-powered code translation system.
Please review and test before using in production.
"""

# utils.py

import re
import uuid

def to_lower_case(s: str) -> str:
    """Convert a string to lower case."""
    return s.lower()

def to_upper_case(s: str) -> str:
    """Convert a string to upper case."""
    return s.upper()

def trim(s: str) -> str:
    """Trim whitespace from the start and end of a string."""
    return s.strip()

def split(s: str, delimiter: str) -> list:
    """Split a string by the given delimiter."""
    return s.split(delimiter)

def is_valid_isbn(isbn: str) -> bool:
    """Validate an ISBN-10 or ISBN-13."""
    isbn = isbn.replace("-", "").replace(" ", "")
    if len(isbn) == 10:
        return _is_valid_isbn10(isbn)
    elif len(isbn) == 13:
        return _is_valid_isbn13(isbn)
    return False

def _is_valid_isbn10(isbn: str) -> bool:
    """Validate an ISBN-10."""
    if not isbn.isdigit() and isbn[-1] not in "0123456789Xx":
        return False
    total = sum((10 - i) * (10 if char in "Xx" else int(char)) for i, char in enumerate(isbn))
    return total % 11 == 0

def _is_valid_isbn13(isbn: str) -> bool:
    """Validate an ISBN-13."""
    if not isbn.isdigit():
        return False
    total = sum((1 if i % 2 == 0 else 3) * int(char) for i, char in enumerate(isbn))
    return total % 10 == 0

def is_valid_email(email: str) -> bool:
    """Validate an email address."""
    email_regex = r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)"
    return re.match(email_regex, email) is not None

def generate_user_id() -> str:
    """Generate a unique user ID."""
    return str(uuid.uuid4())

def generate_transaction_id(counter: int) -> str:
    """Generate a transaction ID using a counter."""
    return f"TX-{counter:08d}"

# Example usage
if __name__ == "__main__":
    print(to_lower_case("Hello World"))
    print(to_upper_case("Hello World"))
    print(trim("   Hello World   "))
    print(split("Hello,World,Python", ','))
    print(is_valid_isbn("0-306-40615-2"))
    print(is_valid_email("example@example.com"))
    print(generate_user_id())
    print(generate_transaction_id(123))