"""
Automatically translated from C++ to Python

Original file: src/Book.cpp
Module: Book

This code was generated by an AI-powered code translation system.
Please review and test before using in production.
"""

class Book:
    def __init__(self, isbn, title, author, year):
        self.isbn = isbn
        self.title = title
        self.author = author
        self.publication_year = year
        self.is_available = True
        self.categories = []
        print(f"Book created: {self.title}")

    def __del__(self):
        print(f"Book destroyed: {self.title}")

    def get_isbn(self):
        return self.isbn

    def get_title(self):
        return self.title

    def get_author(self):
        return self.author

    def get_publication_year(self):
        return self.publication_year

    def get_availability(self):
        return self.is_available

    def get_categories(self):
        return self.categories

    def set_availability(self, available):
        self.is_available = available

    def add_category(self, category):
        self.categories.append(category)

    def display_info(self):
        print(f"ISBN: {self.isbn}")
        print(f"Title: {self.title}")
        print(f"Author: {self.author}")
        print(f"Year: {self.publication_year}")
        print(f"Available: {'Yes' if self.is_available else 'No'}")
        
        if self.categories:
            print("Categories: " + " ".join(self.categories))

    def matches_search(self, query):
        lower_query = query.lower()
        lower_title = self.title.lower()
        lower_author = self.author.lower()

        return (lower_query in lower_title or
                lower_query in lower_author or
                self.isbn == query)

# Example usage
if __name__ == "__main__":
    book = Book("1234567890", "Python Programming", "John Doe", 2021)
    book.add_category("Programming")
    book.add_category("Technology")
    book.display_info()
    print("Matches search 'python':", book.matches_search("python"))
    print("Matches search 'doe':", book.matches_search("doe"))
    print("Matches search '1234567890':", book.matches_search("1234567890"))