"""
Automatically translated from C++ to Python

Original file: src/Library.cpp
Module: Library

This code was generated by an AI-powered code translation system.
Please review and test before using in production.
"""

import sys

class Library:
    def __init__(self, name):
        self.library_name = name
        self.total_borrowed_count = 0
        self.books = {}
        self.users = {}
        print(f"Library created: {self.library_name}")

    def __del__(self):
        print(f"Library closed: {self.library_name}")

    def add_book(self, book):
        isbn = book.get_isbn()
        
        if isbn in self.books:
            print("Book already exists!")
            return False
        
        self.books[isbn] = book
        print(f"Book added to library: {book.get_title()}")
        return True

    def remove_book(self, isbn):
        if isbn not in self.books:
            print("Book not found!")
            return False
        
        del self.books[isbn]
        print("Book removed from library")
        return True

    def find_book(self, isbn):
        return self.books.get(isbn)

    def search_books(self, query):
        results = [book for book in self.books.values() if book.matches_search(query)]
        return results

    def register_user(self, user):
        user_id = user.get_user_id()
        
        if user_id in self.users:
            print("User already registered!")
            return False
        
        self.users[user_id] = user
        print(f"User registered: {user.get_name()}")
        return True

    def remove_user(self, user_id):
        if user_id not in self.users:
            print("User not found!")
            return False
        
        del self.users[user_id]
        print("User removed")
        return True

    def find_user(self, user_id):
        return self.users.get(user_id)

    def borrow_book(self, user_id, isbn):
        user = self.find_user(user_id)
        book = self.find_book(isbn)
        
        if not user:
            print("User not found!")
            return False
        
        if not book:
            print("Book not found!")
            return False
        
        if not book.get_availability():
            print("Book is not available!")
            return False
        
        if not user.can_borrow_more():
            print("User has reached borrowing limit!")
            return False
        
        book.set_availability(False)
        user.borrow_book(isbn)
        self.total_borrowed_count += 1
        
        print("Book borrowed successfully!")
        return True

    def return_book(self, user_id, isbn):
        user = self.find_user(user_id)
        book = self.find_book(isbn)
        
        if not user or not book:
            print("User or book not found!")
            return False
        
        if not user.has_borrowed(isbn):
            print("User hasn't borrowed this book!")
            return False
        
        book.set_availability(True)
        user.return_book(isbn)
        self.total_borrowed_count -= 1
        
        print("Book returned successfully!")
        return True

    def get_total_books(self):
        return len(self.books)

    def get_available_books(self):
        return sum(1 for book in self.books.values() if book.get_availability())

    def get_total_users(self):
        return len(self.users)

    def get_total_borrowed(self):
        return self.total_borrowed_count

    def display_library_info(self):
        print(f"\n=== {self.library_name} ===")
        print(f"Total Books: {self.get_total_books()}")
        print(f"Available Books: {self.get_available_books()}")
        print(f"Total Users: {self.get_total_users()}")
        print(f"Books Borrowed: {self.get_total_borrowed()}")

    def display_all_books(self):
        print("\n=== All Books ===")
        for book in self.books.values():
            book.display_info()
            print("---")

    def display_all_users(self):
        print("\n=== All Users ===")
        for user in self.users.values():
            user.display_info()
            print("---")