"""
Automatically translated from C++ to Python

Original file: src/LibrarySystem.cpp
Module: LibrarySystem

This code was generated by an AI-powered code translation system.
Please review and test before using in production.
"""

import sys

class LibrarySystem:
    def __init__(self, library_name):
        self.is_initialized = False
        self.library = Library(library_name)
        self.transaction_manager = TransactionManager()
        print("Library System created")

    def __del__(self):
        if self.is_initialized:
            self.shutdown()
        print("Library System destroyed")

    def initialize(self):
        if self.is_initialized:
            print("System already initialized!")
            return False
        
        self.is_initialized = True
        print("Library System initialized successfully")
        return True

    def shutdown(self):
        if not self.is_initialized:
            return
        
        self.is_initialized = False
        print("Library System shutting down...")
        
        # Generate final report
        self.generate_system_report()

    def borrow_book_with_transaction(self, user_id, isbn):
        if not self.is_initialized:
            print("System not initialized!")
            return False
        
        success = self.library.borrow_book(user_id, isbn)
        
        if success:
            self.transaction_manager.record_transaction(
                user_id, isbn, TransactionType.BORROW)
        
        return success

    def return_book_with_transaction(self, user_id, isbn):
        if not self.is_initialized:
            print("System not initialized!")
            return False
        
        success = self.library.return_book(user_id, isbn)
        
        if success:
            self.transaction_manager.record_transaction(
                user_id, isbn, TransactionType.RETURN)
        
        return success

    def generate_user_report(self, user_id):
        print("\n=== User Report ===")
        
        user = self.library.find_user(user_id)
        if user:
            user.display_info()
            
            transactions = self.transaction_manager.get_user_transactions(user_id)
            print(f"\nTotal Transactions: {len(transactions)}")
        else:
            print("User not found!")

    def generate_book_report(self, isbn):
        print("\n=== Book Report ===")
        
        book = self.library.find_book(isbn)
        if book:
            book.display_info()
            
            transactions = self.transaction_manager.get_book_transactions(isbn)
            print(f"\nTotal Transactions: {len(transactions)}")
        else:
            print("Book not found!")

    def generate_system_report(self):
        print("\n======================================")
        print("    LIBRARY SYSTEM REPORT")
        print("======================================")
        
        self.library.display_library_info()
        
        print("\n=== Transaction Statistics ===")
        print(f"Total Transactions: {self.transaction_manager.get_total_transactions()}")
        print(f"Borrows: {self.transaction_manager.get_transactions_by_type(TransactionType.BORROW)}")
        print(f"Returns: {self.transaction_manager.get_transactions_by_type(TransactionType.RETURN)}")
        
        print("======================================\n")

    def get_library(self):
        return self.library

    def get_transaction_manager(self):
        return self.transaction_manager


# Placeholder classes and enums for the sake of completeness
class Library:
    def __init__(self, name):
        self.name = name

    def borrow_book(self, user_id, isbn):
        # Implement borrowing logic
        pass

    def return_book(self, user_id, isbn):
        # Implement returning logic
        pass

    def find_user(self, user_id):
        # Implement user finding logic
        pass

    def find_book(self, isbn):
        # Implement book finding logic
        pass

    def display_library_info(self):
        # Implement library info display logic
        pass

class TransactionManager:
    def record_transaction(self, user_id, isbn, transaction_type):
        # Implement transaction recording logic
        pass

    def get_user_transactions(self, user_id):
        # Implement user transactions retrieval logic
        pass

    def get_book_transactions(self, isbn):
        # Implement book transactions retrieval logic
        pass

    def get_total_transactions(self):
        # Implement total transactions count logic
        pass

    def get_transactions_by_type(self, transaction_type):
        # Implement transactions by type retrieval logic
        pass

class TransactionType:
    BORROW = 'BORROW'
    RETURN = 'RETURN'