"""
Automatically translated from C++ to Python

Original file: src/main.cpp
Module: main

This code was generated by an AI-powered code translation system.
Please review and test before using in production.
"""

# Assuming LibrarySystem, Book, and User are defined in library_system.py and utils.py
from library_system import LibrarySystem, Book, User

def main():
    print("==================================")
    print("  Library Management System")
    print("==================================")
    
    # Create library system
    system = LibrarySystem("City Central Library")
    system.initialize()
    
    library = system.get_library()
    
    # Add some books
    book1 = Book("978-0-13-468599-1", "Effective C++", "Scott Meyers", 2005)
    book1.add_category("Programming")
    book1.add_category("C++")
    
    book2 = Book("978-0-321-56384-2", "The C++ Programming Language", "Bjarne Stroustrup", 2013)
    book2.add_category("Programming")
    
    book3 = Book("978-0-201-70353-4", "Modern C++ Design", "Andrei Alexandrescu", 2001)
    book3.add_category("Design Patterns")
    
    library.add_book(book1)
    library.add_book(book2)
    library.add_book(book3)
    
    # Register users
    user1 = User("USER001", "John Doe", "john@example.com")
    user2 = User("USER002", "Jane Smith", "jane@example.com")
    
    library.register_user(user1)
    library.register_user(user2)
    
    # Display initial state
    library.display_library_info()
    
    # Borrow books
    print("\n=== Borrowing Books ===")
    system.borrow_book_with_transaction("USER001", "978-0-13-468599-1")
    system.borrow_book_with_transaction("USER002", "978-0-321-56384-2")
    
    # Display updated state
    library.display_library_info()
    
    # Return books
    print("\n=== Returning Books ===")
    system.return_book_with_transaction("USER001", "978-0-13-468599-1")
    
    # Generate reports
    system.generate_user_report("USER001")
    system.generate_system_report()
    
    # Shutdown
    system.shutdown()
    
    print("\n=== Program Complete ===")

if __name__ == "__main__":
    main()