"""
Automatically translated from C++ to Python

Original file: src/TransactionManager.cpp
Module: TransactionManager

This code was generated by an AI-powered code translation system.
Please review and test before using in production.
"""

import sys
from typing import List, Optional
from dataclasses import dataclass
from enum import Enum
import logging

# Assuming Transaction and TransactionType are defined elsewhere
# from transaction import Transaction, TransactionType

logging.basicConfig(level=logging.INFO)

@dataclass
class Transaction:
    transaction_id: str
    user_id: str
    isbn: str
    transaction_type: 'TransactionType'

    def get_user_id(self) -> str:
        return self.user_id

    def get_isbn(self) -> str:
        return self.isbn

    def get_transaction_id(self) -> str:
        return self.transaction_id

    def get_type(self) -> 'TransactionType':
        return self.transaction_type

    def display_transaction(self):
        logging.info(f"Transaction ID: {self.transaction_id}, User ID: {self.user_id}, ISBN: {self.isbn}, Type: {self.transaction_type}")

class TransactionType(Enum):
    PURCHASE = 1
    RETURN = 2

class TransactionManager:
    def __init__(self):
        self.next_transaction_id = 1
        self.transactions: List[Transaction] = []
        logging.info("Transaction Manager initialized")

    def __del__(self):
        logging.info("Transaction Manager shutdown")

    def record_transaction(self, user_id: str, isbn: str, transaction_type: TransactionType) -> str:
        tx_id = f"TX{self.next_transaction_id:06}"
        self.next_transaction_id += 1
        
        transaction = Transaction(tx_id, user_id, isbn, transaction_type)
        self.transactions.append(transaction)
        
        logging.info(f"Transaction recorded: {tx_id}")
        return tx_id

    def get_user_transactions(self, user_id: str) -> List[Transaction]:
        return [tx for tx in self.transactions if tx.get_user_id() == user_id]

    def get_book_transactions(self, isbn: str) -> List[Transaction]:
        return [tx for tx in self.transactions if tx.get_isbn() == isbn]

    def get_transaction(self, tx_id: str) -> Optional[Transaction]:
        for tx in self.transactions:
            if tx.get_transaction_id() == tx_id:
                return tx
        return None

    def get_total_transactions(self) -> int:
        return len(self.transactions)

    def get_transactions_by_type(self, transaction_type: TransactionType) -> int:
        return sum(1 for tx in self.transactions if tx.get_type() == transaction_type)

    def display_all_transactions(self):
        logging.info("\n=== All Transactions ===")
        for tx in self.transactions:
            tx.display_transaction()
            logging.info("---")

    def display_recent_transactions(self, count: int):
        logging.info("\n=== Recent Transactions ===")
        start = max(0, len(self.transactions) - count)
        for tx in self.transactions[start:]:
            tx.display_transaction()
            logging.info("---")