"""
Automatically translated from C++ to Python

Original file: src/Transaction.cpp
Module: Transaction

This code was generated by an AI-powered code translation system.
Please review and test before using in production.
"""

from datetime import datetime
from enum import Enum

class TransactionType(Enum):
    BORROW = "BORROW"
    RETURN = "RETURN"
    RENEW = "RENEW"
    UNKNOWN = "UNKNOWN"

class Transaction:
    def __init__(self, transaction_id, user_id, isbn, transaction_type):
        self.transaction_id = transaction_id
        self.user_id = user_id
        self.isbn = isbn
        self.type = transaction_type
        self.timestamp = datetime.now()

    def get_transaction_id(self):
        return self.transaction_id

    def get_user_id(self):
        return self.user_id

    def get_isbn(self):
        return self.isbn

    def get_type(self):
        return self.type

    def get_timestamp(self):
        return self.timestamp

    def get_type_string(self):
        return self.type.value

    def display_transaction(self):
        print(f"Transaction ID: {self.transaction_id}")
        print(f"User ID: {self.user_id}")
        print(f"ISBN: {self.isbn}")
        print(f"Type: {self.get_type_string()}")
        print(f"Time: {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}")

# Example usage:
# transaction = Transaction("TX123", "User456", "ISBN789", TransactionType.BORROW)
# transaction.display_transaction()