"""
Automatically translated from C++ to Python

Original file: src/Utils.cpp
Module: Utils

This code was generated by an AI-powered code translation system.
Please review and test before using in production.
"""

import random
import string

def to_lower_case(s: str) -> str:
    """Convert a string to lowercase."""
    return s.lower()

def to_upper_case(s: str) -> str:
    """Convert a string to uppercase."""
    return s.upper()

def trim(s: str) -> str:
    """Trim leading and trailing spaces from a string."""
    return s.strip()

def split(s: str, delimiter: str) -> list:
    """Split a string by a given delimiter and trim each part."""
    return [part.strip() for part in s.split(delimiter)]

def is_valid_isbn(isbn: str) -> bool:
    """Check if a string is a valid ISBN-10 or ISBN-13."""
    if len(isbn) not in (10, 13):
        return False
    return all(c.isdigit() or c == '-' for c in isbn)

def is_valid_email(email: str) -> bool:
    """Check if a string is a valid email address."""
    return '@' in email and '.' in email

def generate_user_id() -> str:
    """Generate a random user ID."""
    return f"USER{random.randint(100000, 999999)}"

def generate_transaction_id(counter: int) -> str:
    """Generate a transaction ID with a given counter."""
    return f"TX{counter:08}"

# Example usage
if __name__ == "__main__":
    print(to_lower_case("HELLO WORLD"))
    print(to_upper_case("hello world"))
    print(trim("   hello world   "))
    print(split("one, two, three", ','))
    print(is_valid_isbn("978-3-16-148410-0"))
    print(is_valid_email("example@example.com"))
    print(generate_user_id())
    print(generate_transaction_id(42))